//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 MIPFaster.rc 使用
//
#define IDD_MIPFASTER_DIALOG            102
#define IDR_MAINFRAME                   128
#define ID_INDICATOR_POS                132
#define ID_INDICATOR_RGB                133
#define IDD_DIALOG_HSV                  133
#define ID_INDICATOR_HSV                134
#define ID_INDICATOR_TIME               135
#define IDD_DIALOG_LINEAR_PARA          135
#define IDD_DIALOG_SEGLINEAR_PARA       137
#define IDD_DIALOG_OPERATION            139
#define IDD_DIALOG_ROTATE               141
#define IDC_BUTTON2                     1006
#define IDC_BUTTON_HSV                  1006
#define IDC_BUTTON_CANCLE               1006
#define IDC_BUTTON_OPERA_CLOSE          1006
#define IDC_BUTTON3                     1007
#define IDC_BUTTON_LINEARTRANS          1007
#define IDC_BUTTON4                     1008
#define IDC_BUTTON_SEGTRANS             1008
#define IDC_BUTTON5                     1009
#define IDC_BUTTON_HISTOGRAM_EQ         1009
#define IDC_BUTTON6                     1010
#define IDC_BUTTON_HIST_SPEC            1010
#define IDC_BUTTON7                     1011
#define IDC_BUTTON_LOWPASS_T            1011
#define IDC_BUTTON8                     1012
#define IDC_BUTTON_HIGHPASS_T           1012
#define IDC_BUTTON9                     1013
#define IDC_BUTTON_MED_FILTER           1013
#define IDC_BUTTON10                    1014
#define IDC_BUTTONMAX_FILTER            1014
#define IDC_BUTTON11                    1015
#define IDC_BUTTON_MIN_FILTER           1015
#define IDC_BUTTON12                    1016
#define IDC_BUTTON_PSE_COLOR            1016
#define IDC_RADIO1                      1017
#define IDC_RADIO_FILTER3               1017
#define IDC_RADIO2                      1018
#define IDC_RADIO_FILTER5               1018
#define IDC_RADIO3                      1019
#define IDC_RADIO_FILTER7               1019
#define IDC_BUTTON13                    1020
#define IDC_BUTTON_PLUS                 1020
#define IDC_BUTTON14                    1021
#define IDC_BUTTON_MINUS                1021
#define IDC_BUTTON15                    1022
#define IDC_BUTTON_MULTI                1022
#define IDC_BUTTON16                    1023
#define IDC_BUTTON_DIV                  1023
#define IDC_BUTTON17                    1024
#define IDC_BUTTON_AND                  1024
#define IDC_BUTTON18                    1025
#define IDC_BUTTON_OR                   1025
#define IDC_BUTTON19                    1026
#define IDC_BUTTON_NOT                  1026
#define IDC_BUTTON20                    1027
#define IDC_BUTTON_XOR                  1027
#define IDC_BUTTON21                    1028
#define IDC_BUTTON_FILPX                1028
#define IDC_BUTTON22                    1029
#define IDC_BUTTON_FILPY                1029
#define IDC_BUTTON23                    1030
#define IDC_BUTTON_FOT90                1030
#define IDC_BUTTON24                    1031
#define IDC_BUTTON_FOT180               1031
#define IDC_SLIDER1                     1032
#define IDC_SLIDER_SHRINK               1032
#define IDC_SAVE                        1033
#define IDC_BUTTON26                    1034
#define IDC_BUTTON_FFT                  1034
#define IDC_BUTTON27                    1035
#define IDC_BUTTON_IFFT                 1035
#define IDC_COMBO2                      1036
#define IDC_COMBO_FILTER                1036
#define IDC_EDIT1                       1038
#define IDC_EDIT2                       1039
#define IDC_BUTTON29                    1040
#define IDC_BUTTON_FILTER_RUN           1040
#define IDC_EDIT3                       1041
#define IDC_BUTTON30                    1042
#define IDC_BUTTON_INV                  1042
#define IDC_EDIT4                       1043
#define IDC_EDIT5                       1044
#define IDC_EDIT_WIN_K                  1044
#define IDC_BUTTON31                    1045
#define IDC_BUTTON_WINNER               1045
#define IDC_EDIT6                       1046
#define IDC_EDIT_SEG_PARA               1046
#define IDC_BUTTON32                    1047
#define IDC_BUTTON_MANSRG               1047
#define IDC_BUTTON33                    1048
#define IDC_BUTTON_OSTSEG               1048
#define IDC_BUTTON34                    1049
#define IDC_BUTTON_GROW                 1049
#define IDC_BUTTON35                    1050
#define IDC_BUTTON_MERGE                1050
#define IDC_BUTTON36                    1051
#define IDC_BUTTON_OPENING              1051
#define IDC_BUTTON37                    1052
#define IDC_BUTTON_CLOSING              1052
#define IDC_COMBO3                      1053
#define IDC_COMBO_MORPH                 1053
#define IDC_BUTTON38                    1054
#define IDC_BUTTON_EROSION              1054
#define IDC_BUTTON39                    1055
#define IDC_BUTTON_DIALATION            1055
#define IDC_EDIT7                       1056
#define IDC_BUTTON40                    1057
#define IDC_BUTTON_SKELETON             1057
#define IDC_IMAGE_ORGIN                 1058
#define IDC_IMAGE_TRANS                 1059
#define IDC_OPEN                        1060
#define IDC_CLOSE                       1061
#define IDC_SLIDER_S                    1062
#define IDC_SLIDER_V                    1063
#define IDC_SLIDER_H                    1064
#define IDC_EDIT_H                      1065
#define IDC_EDIT_S                      1066
#define IDC_EDIT_V                      1067
#define ID_APPLY                        1068
#define ID_HSV_APPLY                    1068
#define IDC_HSV_CLOSE                   1069
#define IDC_BUTTON_TO_GRAY              1070
#define IDC_BUTTON_LINEAR_CLOSE         1071
#define IDC_EDIT_LINEAR_PARA1           1072
#define IDC_EDIT_LINEAR_PARA2           1073
#define ID_BUTTON_LINEAR_CONFIRM        1074
#define IDC_EDIT_LINEAR_PARA3           1075
#define IDC_BUTTON_YES                  1075
#define IDC_EDIT_LINEAR_PARA4           1076
#define IDC_BUTTON_OPERA_OPEN           1076
#define IDC_STATIC_OPERA_IMAGEB         1077
#define IDC_EDIT_ALPHA                  1078
#define IDC_EDIT_BETA                   1079
#define IDC_BUTTON_ANGLE_YES            1080
#define IDC_STATIC_ROTATE_YES           1081
#define IDC_CANCAL                      1082
#define IDC_EDIT_ANGLE                  1083
#define IDC_EDIT_FREN                   1084
#define IDC_EDIT_RANK                   1085
#define IDC_EDIT_INV_L                  1086
#define IDC_EDIT_WIN_L                  1087

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
